// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'ICil:mediaPlay': typeof import('~icons/cil/media-play')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    'IFaSolid:angleDoubleLeft': typeof import('~icons/fa-solid/angle-double-left')['default']
    'IFaSolid:angleDoubleRight': typeof import('~icons/fa-solid/angle-double-right')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'IFileIcons:configPython': typeof import('~icons/file-icons/config-python')['default']
    'IFileIcons:testPython': typeof import('~icons/file-icons/test-python')['default']
    IFluentSettings32Regular: typeof import('~icons/fluent/settings32-regular')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'IMdi:languagePython': typeof import('~icons/mdi/language-python')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}

export { }
